server:
  port: 8081

spring:
  application:
    name: api-recantocity
  datasource:
    url: jdbc:h2:mem:partner_database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect