name: Criar Pull Request

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  Test:
    name: Test
    uses: ./.github/workflows/test.yml